### PR TITLE
Added explicict LC_ALL

### PR DESCRIPTION
**Pull request by cyberone**

### CODE REVIEW

**Comment by cyberone** [comment]
@longtimeago please see it again.

**Comment by longtimeago** [comment]
@rultor please, merge

**Comment by longtimeago** [comment]
@cyberone sorry for late answer

**Comment by longtimeago** [comment]
@cyberone One test is failed
```
Failed tests: VerboseProcessTest.runsACommandLineScript:74 Expected: a string containing "?!" but: was "hey ?! "
```

**Comment by longtimeago** [comment]
@cyberone see logs http://www.rultor.com/t/1569-69790429

**Comment by cyberone** [comment]
@longtimeago I see that rultor runs in a 8-bit locale. Is there a way to change it's environment?

**Comment by longtimeago** [comment]
@cyberone It's a question to @yegor256

**Comment by yegor256** [comment]
@cyberone everything is possible. submit a bug to rultor project and we'll discuss it there

**Comment by cyberone** [comment]
@yegor256 there is a way to change rultor's environment. If further test fails, I might need to check rultor's Dockerfile.

**Comment by longtimeago** [comment]
@cyberone any progress?

**Comment by cyberone** [comment]
@longtimeago we'd better ask @rultor to merge and see what happens.

**Comment by cyberone** [comment]
@rultor merge

**Comment by longtimeago** [comment]
@cyberone let's try

**Comment by longtimeago** [comment]
@rultor please, merge

**Comment by longtimeago** [comment]
@cyberone same error

**Comment by cyberone** [comment]
@yegor256 is this PR https://github.com/yegor256/rultor/pull/296 in production?

**Comment by yegor256** [comment]
@cyberone currently deployed version is [1.47.1](https://github.com/yegor256/rultor/releases), this is the list of commits not deployed yet: https://github.com/yegor256/rultor/compare/1.47.1...master

**Comment by cyberone** [comment]
@yegor256 @longtimeago the task is reassigned from me  I'll try some attempts later if the bug is still open, may I?

**Comment by yegor256** [comment]
@cyberone sure why not

**Comment by longtimeago** [comment]
@cyberone any news?

**Comment by longtimeago** [comment]
@cyberone any news here?

**Comment by cyberone** [comment]
Not yet. Too busy, need more time.

-----Исходное сообщение-----
От: "Paul Polishchuk" <notifications@github.com>
Отправлено: ‎03.‎02.‎2015 18:15
Кому: "jcabi/jcabi-log" <jcabi-log@noreply.github.com>
Копия: "cyberone" <alopen@yandex.ru>
Тема: Re: [jcabi-log] Added explicict LC_ALL (#45)

@cyberone any news here?

**Comment by longtimeago** [comment]
@cyberone OK then, please close current PR

**Comment by dmarkov** [comment]
@longtimeago thanks, paid, **29 mins** to your account, payment ID is `51519736`. added +29 to your rating, now it is equal to [+1684](http://www.netbout.com/b/35024?open=rating)

**Pull request closed without merging**
