### PR TITLE
make jcabi-log a valid OSGI bundle

### PR DESCRIPTION
**Pull request by gdelafosse**
use the maven-bundle-plugin to make jcabi-log a valid OSGI bundle

### CODE REVIEW

**Comment by dmarkov** [comment]
@gdelafosse Thanks, I will find someone to review this PR soon

**Comment by dmarkov** [comment]
@yegor256 the PR is rather short, please review it

**Comment by yegor256** [comment]
@rultor merge it

**Comment by dmarkov** [comment]
@yegor256 Thanks a lot, I just topped your account for **16 mins**, transaction ID `000-57f92f41`, total time was 21 hours and 8 mins... you're getting extra minutes here (c=1)... +16 added to your rating, current score is: [+6806](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy now pls

**Pull request merged**
