### PR TITLE
Add Javadoc badge with automatic version detection

### PR DESCRIPTION
**Pull request by valery1707**

### CODE REVIEW

**Comment by dmarkov** [comment]
@valery1707 I will find a reviewer for your pull requests shortly, thanks for contribution!

**Comment by dmarkov** [comment]
@yegor256 pull request is rather short, review it please

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@yegor256 Much obliged! I have added **16 mins** to your account in payment "000-b951b7bb", 21 hours and 16 mins spent... you're getting extra minutes here (c=1)... added +16 to your rating, now it is equal to [+4191](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy now pls

**Pull request merged**
