### PR TITLE
Look for balanced curly brace end while searching for arguments. Fixes #53.

### LINKED ISSUE #53: Coloring %c{1} prevents coloring from stopping
First, thanks for the awesome component!

Using for example 

```
%d{HH:mm:ss,SSS} [%t] %color{%-5p} %color-blue{%c{1}} - %m%n
```

returns lines that are completely blue after debug level (incorrect, only class name should be blue)

But using:

```
%d{HH:mm:ss,SSS} [%t] %color{%-5p} %color-blue{%c} - %m%n
```

returns correctly colored lines.

Br. Jaakko

### PR DESCRIPTION
**Pull request by csabakos**
Many thanks for your contribution, we truly appreciate it. We will appreciate it even more, if you make sure that you can say "YES" to each point in this short checklist:

  - You made a small amount of changes (less than 100 lines, less than 10 files)
  - You made changes related to only one bug (create separate PRs for separate problems)
  - You are ready to defend your changes (there will be a code review)
  - You don't touch what you don't understand
  - You ran the build locally and it passed

This article will help you understand what we are looking for: http://www.yegor256.com/2015/02/09/serious-code-reviewer.html

Thank you for your contribution!

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#105](https://github.com/jcabi/jcabi-log/issues/105) is now in scope, role is `REV`

**Comment by csabakos** [comment]
Fixes #53

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#105](https://github.com/jcabi/jcabi-log/issues/105); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#105](https://github.com/jcabi/jcabi-log/issues/105); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#105](https://github.com/jcabi/jcabi-log/issues/105); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-log#105` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#105](https://github.com/jcabi/jcabi-log/issues/105) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Pull request merged**
